/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MasukRouteImport } from './routes/masuk'
import { Route as PpdbRouteImport } from './routes/ppdb'
import { Route as SppRouteImport } from './routes/spp'
import { Route as JenjangLevelRouteImport } from './routes/jenjang.$level'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MasukRoute = MasukRouteImport.update({
  id: '/masuk',
  path: '/masuk',
  getParentRoute: () => rootRouteImport,
} as any)
const PpdbRoute = PpdbRouteImport.update({
  id: '/ppdb',
  path: '/ppdb',
  getParentRoute: () => rootRouteImport,
} as any)
const SppRoute = SppRouteImport.update({
  id: '/spp',
  path: '/spp',
  getParentRoute: () => rootRouteImport,
} as any)
const JenjangLevelRoute = JenjangLevelRouteImport.update({
  id: '/jenjang/$level',
  path: '/jenjang/$level',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/masuk': typeof MasukRoute
  '/ppdb': typeof PpdbRoute
  '/spp': typeof SppRoute
  '/jenjang/$level': typeof JenjangLevelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/masuk': typeof MasukRoute
  '/ppdb': typeof PpdbRoute
  '/spp': typeof SppRoute
  '/jenjang/$level': typeof JenjangLevelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/masuk': typeof MasukRoute
  '/ppdb': typeof PpdbRoute
  '/spp': typeof SppRoute
  '/jenjang/$level': typeof JenjangLevelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/masuk' | '/ppdb' | '/spp' | '/jenjang/$level'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/masuk' | '/ppdb' | '/spp' | '/jenjang/$level'
  id: '__root__' | '/' | '/masuk' | '/ppdb' | '/spp' | '/jenjang/$level'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MasukRoute: typeof MasukRoute
  PpdbRoute: typeof PpdbRoute
  SppRoute: typeof SppRoute
  JenjangLevelRoute: typeof JenjangLevelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masuk': {
      id: '/masuk'
      path: '/masuk'
      fullPath: '/masuk'
      preLoaderRoute: typeof MasukRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ppdb': {
      id: '/ppdb'
      path: '/ppdb'
      fullPath: '/ppdb'
      preLoaderRoute: typeof PpdbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spp': {
      id: '/spp'
      path: '/spp'
      fullPath: '/spp'
      preLoaderRoute: typeof SppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jenjang/$level': {
      id: '/jenjang/$level'
      path: '/jenjang/$level'
      fullPath: '/jenjang/$level'
      preLoaderRoute: typeof JenjangLevelRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MasukRoute: MasukRoute,
  PpdbRoute: PpdbRoute,
  SppRoute: SppRoute,
  JenjangLevelRoute: JenjangLevelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
