/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JenjangLevelRouteImport } from './routes/jenjang.$level'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JenjangLevelRoute = JenjangLevelRouteImport.update({
  id: '/jenjang/$level',
  path: '/jenjang/$level',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/jenjang/$level': typeof JenjangLevelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/jenjang/$level': typeof JenjangLevelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/jenjang/$level': typeof JenjangLevelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/jenjang/$level'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/jenjang/$level'
  id: '__root__' | '/' | '/jenjang/$level'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JenjangLevelRoute: typeof JenjangLevelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jenjang/$level': {
      id: '/jenjang/$level'
      path: '/jenjang/$level'
      fullPath: '/jenjang/$level'
      preLoaderRoute: typeof JenjangLevelRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JenjangLevelRoute: JenjangLevelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
